# netlify.toml
[build]
  # Your existing build settings
  publish = "dist"  # or whatever your build folder is
  command = "npm run build"  # or your build command

[functions]
  directory = "netlify/functions"

# Redirect rules for SPA (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = [""], Country = [""]}

# Function-specific settings (optional)
[[functions]]
  function = "send-slack-notification"
  included_files = ["netlify/functions/send-slack-notification.js"]